### ISSUE TITLE
Allow Peril to run Danger Swift and Danger Ruby configs

### ISSUE THREAD

**Issue by freak4pc** [danger/peril#185]
This is just a thought I've had - 

Is there anything preventing adding some way to identity and execute (even via some raw `exec`) the Dangerfile for ruby-based or swift-based Danger setups ? 

I wandered through the code but it is a relatively massive codebase (+ TS isn't something I work with unfortunately besides hobby) and some things like `Executor` seem to already be bundled so a bit hard to drill into. 

Is this something achievable? @orta, if you could direct me to where Danger actually runs inside the Peril code I'd love to just hack on it and experiment. 

Would love your thoughts on this :)

🤓

**Comment by orta** [comment]
Hrm, so the `danger process` aspect is feasible - if you're willing to host your own box which can do it. 

Peril is moving to a true process separated environment, so that execution of a dangerfile is on a completely separate server #183 - this will use the exact same infra as `danger process` under the hood (sending a DSL as JSON to a server, expecting a JSON response back) which will make it just as possible to have a ruby/swift/go/rust/whatever server that handles it instead.

Right now I plan to move the JS execution environment to be on AWS (a public peril for anyone to sign up to will require considerable horizontal scale) but there's no reason to think that building out support for arbitrary endpoints would be a problem.

**Comment by orta** [comment]
* WRT Swift, that could be tough, maybe there's an eval/script execution mode I don't know about which can be called from a vapor server

* WRT Ruby, you'd have to maybe add support to Danger Ruby to handle a Danger JS PR (lols) 

It's definitely a lot of work though, that I'll support, but probably won't do myself

**Comment by freak4pc** [comment]
Won't have time for this anytime soon and seems like It might just be easier to write myself some JS/TS Dangerfiles ;) 

Thanks for being open minded about this though.

Shai.
